worker:
  pipPackages: >-
      gcsfs
      git+https://github.com/pydata/xarray.git@master
      git+https://github.com/alimanfoo/zarr.git@master
  condaPackages: >-
      scipy
      netcdf4
  limits:
    cpu: 2
    memory: 7.5GiB
  replicas: 6

jupyter:
  pipPackages: >-
      gcsfs
      git+https://github.com/pydata/xarray.git@master
      git+https://github.com/alimanfoo/zarr.git@master
  condaPackages: >-
      scipy
      netcdf4
  replicas: 0
