{
 "title": "Pangeo",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(averageSeries(worldping.pangeo_informaticslab_co_uk.london.https.ok_state), 100)"
    }
   ]
  },
  {
   "title": "Registered users",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"pangeo\",persistentvolumeclaim=~\"claim-.*\"})",
     "target": "scale(averageSeries(worldping.pangeo_informaticslab_co_uk.london.https.ok_state), 100)"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"jupyter-.*\",namespace=\"pangeo\"})",
     "target": "scale(averageSeries(worldping.pangeo_informaticslab_co_uk.london.https.ok_state), 100)"
    }
   ]
  },
  {
   "title": "Usage Map",
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"jupyter-.*\"})"
    }
   ]
  },
  {
   "title": "Total home directory size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"pangeo\",persistentvolumeclaim=~\"claim-.*\"})"
    }
   ]
  },
  {
   "title": "Dask clusters",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (cluster) (\n    label_replace(\n    rate(\n       kube_pod_info{pod=~\"dask-.*\",namespace=\"pangeo\"}[1h]\n    ), \"cluster\", \"$1\", \"pod\", \"dask-([a-zA-Z0-9]*-.*)-.*\")\n))",
     "target": "scale(averageSeries(worldping.pangeo_informaticslab_co_uk.london.https.ok_state), 100)"
    }
   ]
  },
  {
   "title": "Dask workers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"dask-.*\",namespace=\"pangeo\"})",
     "target": "scale(averageSeries(worldping.pangeo_informaticslab_co_uk.london.https.ok_state), 100)"
    }
   ]
  },
  { "title": "Notebooks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "alias": "$tag_pod_name",
     "expr": "sum by (user) (\n    label_replace(\n        rate(container_cpu_user_seconds_total{pod_name=~\"jupyter-.*\",namespace=\"pangeo\"}[1h]), \n             \"user\", \"$1\", \"pod_name\", \"jupyter-([a-zA-Z0-9]*)\"\n    )\n)",
     "groupBy": [
      { "params": [ "pod_name" ], "type": "tag" }
     ],
     "legendFormat": "{{user}}",
     "measurement": "cpu/usage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "labels",
       "operator": "=",
       "value": "app:jupyterhub,component:singleuser-server,heritage:jupyterhub"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_pod_name",
     "expr": "sum by (user) (\n    label_replace(\n        container_memory_usage_bytes{pod_name=~\"jupyter-.*\",namespace=\"pangeo\"}, \"user\", \"$1\", \"pod_name\", \"jupyter-([a-zA-Z0-9]*)\"\n    )\n)",
     "groupBy": [
      { "params": [ "pod_name" ], "type": "tag" }
     ],
     "legendFormat": "{{user}}",
     "measurement": "memory/usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "labels",
       "operator": "=",
       "value": "app:jupyterhub,component:singleuser-server,heritage:jupyterhub"
      }
     ]
    }
   ]
  },
  { "title": "Dask clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "alias": "$tag_pod_name",
     "expr": "sum by (cluster) (\n    label_replace(\n    rate(\n       container_cpu_user_seconds_total{pod_name=~\"dask-.*-.*\",namespace=\"pangeo\"}[1h]\n    ), \"cluster\", \"$1\", \"pod_name\", \"dask-([a-zA-Z0-9]*-.*)-.*\")\n)",
     "groupBy": [
      { "params": [ "pod_name" ], "type": "tag" }
     ],
     "legendFormat": "{{cluster}}",
     "measurement": "cpu/usage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "labels",
       "operator": "=",
       "value": "app:jupyterhub,component:singleuser-server,heritage:jupyterhub"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_pod_name",
     "expr": "sum by (cluster) (\n    label_replace(\n       container_memory_usage_bytes{pod_name=~\"dask-.*\",namespace=\"pangeo\"}, \"cluster\", \"$1\", \"pod_name\", \"dask-([a-zA-Z0-9]*-.*)-.*\"\n       )\n)",
     "groupBy": [
      { "params": [ "pod_name" ], "type": "tag" }
     ],
     "legendFormat": "{{cluster}}",
     "measurement": "memory/usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "labels",
       "operator": "=",
       "value": "app:jupyterhub,component:singleuser-server,heritage:jupyterhub"
      }
     ]
    }
   ]
  }
 ]
}