worker:
  spec:
    containers:
    - args: [dask-worker, --nthreads, '2', --no-bokeh, --memory-limit, 8GB]
      image: daskdev/pangeo-worker:latest
      name: dask-worker
      security_context:
        capabilities:
          add: [SYS_ADMIN]
        privileged: true
      volume_mounts:
        - mountPath: /dev/fuse
          name: fuse
      env:
        - name: EXTRA_PIP_PACKAGES
          value: git+https://github.com/dask/distributed
        - name: GCSFUSE_BUCKET
          value: pangeo-data
      resources:
        - limits:
            cpu: "3"
            memory: 8G
        - requests:
            cpu: "2"
            memory: 8G
    restart_policy: Never

